name: boa_prova_minha_princesa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  assets_audio_player: ^3.1.1
  audioplayers: ^6.1.2
  flutter:
    sdk: flutter
  rive: ^0.13.20
  particles_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/music.mp3

